### ISSUE TITLE
Support for React Hooks

### ISSUE THREAD

**Issue by bsaphier** [ngReact/ngReact#225]
I can not get hooks to work in my components being rendered by ngReact.

In my `.bowerrc` I have the following code:
```
  "ignoredDependencies": [
    "react",
    "react-dom"
  ]
```
In my HTML I am including a script tag for react version: 16.8.6
And when I console log `React.version` from my react component I get `16.8.6` as expected

But I still get the following error when I try to use hooks in my React components being rendered by ngReact:
```
Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at k (http://10.200.10.1:3030/react/build/common.bundle.js:14:1155)
    at Te (http://10.200.10.1:3030/react/build/common.bundle.js:14:17525)
    at useState (http://10.200.10.1:3030/react/build/common.bundle.js:14:26442)
    at R (http://10.200.10.1:3030/react/build/common.bundle.js:135:211496)
    at renderWithHooks (http://10.200.10.1:3030/bower/react-dom/react-dom.development.js:13073:18)
    at mountIndeterminateComponent (http://10.200.10.1:3030/bower/react-dom/react-dom.development.js:15155:13)
    at beginWork (http://10.200.10.1:3030/bower/react-dom/react-dom.development.js:15760:16)
    at performUnitOfWork (http://10.200.10.1:3030/bower/react-dom/react-dom.development.js:19447:12)
    at workLoop (http://10.200.10.1:3030/bower/react-dom/react-dom.development.js:19487:24)
    at HTMLUnknownElement.callCallback (http://10.200.10.1:3030/bower/react-dom/react-dom.development.js:143:14)
```

I also tried copying react & react-dom from `node_modules` to `bower_components` and added this to my webpack config but the result was the same:
```
    alias: {
      react: path.resolve(__dirname, '../bower_components/react/index.js'),
      'react-dom': path.resolve(__dirname, '../bower_components/react-dom/index.js')
    },
    modules: [path.resolve(__dirname, '../bower_components'), 'node_modules']
```

Am I doing something wrong or are react hooks just incompatible with ngReact?

**Comment by bsaphier** [comment]
I was able to get hooks to work with the following:

1. Added a file to my project that I named `reactShim.js` with this content:
```javascript
// module.exports instead of `export default` so that the entire top-level API is exported
module.exports = window.React;
```

2. Installed `imports-loader` and added the following to my webpack config:
```javascript
module.exports = {
  // ...the rest of the config
  resolve: {
    alias: {
      // added the following line
      react: path.resolve(__dirname, 'reactShim.js')
    }
  },
  module: {
    rules: [
      {
        // added the following two lines
        test: /\.m?js$/,
        use: 'imports-loader?react=>window.React'
      },
      // etc. etc.
    ]
  }
};
```

Is there a better way to do this??

**Comment by kasperp** [comment]
Thanks for your request. I doubt ngReact will get updated to support hooks, I suggest you look at some alternatives like

https://github.com/microsoft/angular-react or https://github.com/coatue-oss/react2angular
